### ISSUE TITLE
MongoDB setup, monguse 설정

### ISSUE THREAD

**Issue by anzmin** [skkuse/2023spring_41class_team3#11]
## Description
mongoDB 설정과 ORM인 monguse 적용

## Todo
- [x] 로컬 mongoDB 설치
- [x] nestJS에 db config 설정
- [x] env 파일 분리
- [x] monguse 적용
- [x] example code 작성
- [x] mongo-express 설정 (web DB GUI)
- [x] mongoDB, mongo-express docker-compose script 생성
