### ISSUE TITLE
코딩 테스트 관련 기능 구현

### ISSUE THREAD

**Issue by anzmin** [skkuse/2023spring_41class_team3#22]
## Description
코딩 테스트와 관련된 기능을 구현

코딩 테스트 시작 모달과 관련된 problem 가져오는 기능은 
아직 problem api가 구현이 되지 않았기 때문에 나중에 구현

## Todo
- [ ] coding test domain 생성
- [ ] 코딩 테스트 시간 관리
- [ ] 샘플 테스트 케이스 채점 api end-point 구현
- [ ] 실제 제출 채점 api end-point 구현
- [ ] 각각의 case가 채점이 되면 바로 전달되도록 server sent event 도입
    - SSE는 위의 코딩 테스트 시간 종료에도 쓰이므로 사용할 예정
 - [ ] 시험 종료 api end-point 구현
