### ISSUE TITLE
CI/CD 및 배포

### ISSUE THREAD

**Issue by anzmin** [skkuse/2023spring_41class_team3#25]
## Description
CI/CD script 작성
AWS EC2 인스턴스에 배포 후 도메인 연결

## Todo
- [ ] front delopy script
- [ ] back delopy script
- [ ] aws 도메인 연결
